---
abstract: ~
author:
  - 'Toru Yamaguchi <zigorou@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Requires-Env
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Test::Builder::Module: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zigorou/p5-test-requires-env.git
version: 0.01
